name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:

jobs:
  go-test:
    name: Go unit tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app   # ← Go 소스가 있는 폴더

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'   # 사용 버전에 맞게 조정 (예: 1.21.x, 1.23.x)
          cache: true

      - name: Download deps
        run: go mod download

      - name: Run tests (with race & coverage)
        run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Coverage summary
        run: |
          go tool cover -func=coverage.out | tee coverage.txt

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage
          path: app/coverage.out
