name: CI
on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # 1) 기능 테스트: go test (race 포함, 커버리지 파일 생성 → 다음 job에서 사용)
  go-functional-tests:
    name: 1) Functional tests (go test)
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: app } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          cache: true
      - run: go mod download
      - name: Run unit/integration tests
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage
          path: app/coverage.out